In [1]:
import pandas as pd

In [41]:
hospital_bed_dataset = pd.read_csv('usa-hospital-beds_dataset_usa-hospital-beds.csv')
counties_dataset = pd.read_csv('us-counties.csv')
states_dataset = pd.read_csv('us-states.csv')

In [42]:
hospital_bed_dataset.head(10)

,X,Y,OBJECTID,HOSPITAL_NAME,HOSPITAL_TYPE,HQ_ADDRESS,HQ_ADDRESS1,HQ_CITY,HQ_STATE,HQ_ZIP_CODE,...,CNTY_FIPS,FIPS,NUM_LICENSED_BEDS,NUM_STAFFED_BEDS,NUM_ICU_BEDS,ADULT_ICU_BEDS,PEDI_ICU_BEDS,BED_UTILIZATION,Potential_Increase_In_Bed_Capac,AVG_VENTILATOR_USAGE
0,-112.066157,33.495498,1,Phoenix VA Health Care System (AKA Carl T Hayd...,VA Hospital,650 E Indian School Rd,NaN,Phoenix,AZ,85012,...,13.0,4013.0,62.0,62.0,0,0,NaN,NaN,0,0.0
1,-110.965885,32.181263,2,Southern Arizona VA Health Care System,VA Hospital,3601 S 6th Ave,NaN,Tucson,AZ,85723,...,19.0,4019.0,295.0,295.0,2,2,NaN,NaN,0,2.0
2,-119.779742,36.773323,3,VA Central California Health Care System,VA Hospital,2615 E Clinton Ave,NaN,Fresno,CA,93703,...,19.0,6019.0,54.0,54.0,2,2,NaN,NaN,0,2.0
3,-72.957610,41.284400,4,VA Connecticut Healthcare System - West Haven ...,VA Hospital,950 Campbell Ave,NaN,West Haven,CT,6516,...,9.0,9009.0,216.0,216.0,1,1,NaN,NaN,0,2.0
4,-75.606533,39.740206,5,Wilmington VA Medical Center,VA Hospital,1601 Kirkwood Hwy,NaN,Wilmington,DE,19805,...,3.0,10003.0,62.0,62.0,0,0,NaN,NaN,0,1.0
5,-77.011195,38.930682,6,Washington DC VA Medical Center,VA Hospital,50 Irving St Nw,NaN,Washington,DC,20422,...,1.0,11001.0,164.0,164.0,1,1,NaN,NaN,0,2.0
6,-82.345254,29.636989,7,North Florida/South Georgia Veterans Health Sy...,VA Hospital,1601 Sw Archer Rd,NaN,Gainesville,FL,32608,...,1.0,12001.0,432.0,278.0,2,2,NaN,NaN,154,2.0
7,-116.190185,43.621035,8,Boise VA Medical Center,VA Hospital,500 W Fort St,NaN,Boise,ID,83702,...,1.0,16001.0,46.0,46.0,1,1,NaN,NaN,0,1.0
8,-93.721683,32.503101,9,Overton Brooks VA Medical Center,VA Hospital,510 E Stoner Ave,NaN,Shreveport,LA,71101,...,17.0,22017.0,111.0,111.0,1,1,NaN,NaN,0,2.0
9,-90.105308,32.325487,10,Merit Health River Oaks (FKA River Oaks Hospit...,Short Term Acute Care Hospital,1030 River Oaks Dr,NaN,Flowood,MS,39232,...,121.0,28121.0,160.0,160.0,10,10,20.0,0.279868,0,2.0

In [43]:
counties_dataset.head(10)

         date       county       state     fips  cases  deaths
0  2020-01-21    Snohomish  Washington  53061.0      1       0
1  2020-01-22    Snohomish  Washington  53061.0      1       0
2  2020-01-23    Snohomish  Washington  53061.0      1       0
3  2020-01-24         Cook    Illinois  17031.0      1       0
4  2020-01-24    Snohomish  Washington  53061.0      1       0
5  2020-01-25       Orange  California   6059.0      1       0
6  2020-01-25         Cook    Illinois  17031.0      1       0
7  2020-01-25    Snohomish  Washington  53061.0      1       0
8  2020-01-26     Maricopa     Arizona   4013.0      1       0
9  2020-01-26  Los Angeles  California   6037.0      1       0

In [44]:
unique_counties_dataset = states_dataset.groupby("county")["cases", "deaths"].sum()

KeyError: 'county'

In [ ]:
unique_counties_dataset.head()

In [ ]:
unique_counties_dataset.columns

In [ ]:
unique_hospital_beds_dataset = hospital_bed_dataset.groupby("HQ_CITY")["NUM_LICENSED_BEDS"].sum()

In [ ]:
unique_hospital_beds_dataset.head()

In [ ]:
unique_hospital_beds_dataset.columns = ["NUM_LICENSED_BEDS"]

In [ ]:
unique_hospital_beds_dataset.shape

In [ ]:
# currently the problem is that we do not have county-wise data for licensed beds 
# we cannot do state-wise because then the data would only have about 50 rows